version: "3"
services:
  web:
    container_name: appearence_web
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
    - "3001:3001"
    - "9229:9229"
    volumes:
      - .:/app
    depends_on:
    - db
    networks:
    - appearence_network

  db:
    container_name: appearence_db
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appearence
    ports:
    - "5432:5432"
    networks:
    - appearence_network

networks:
  appearence_network:
    driver: bridge
